# Generated by Django 3.2.5 on 2021-08-08 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_rename_category_meals_categorya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
        migrations.RemoveField(
            model_name='category',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='update_at',
        ),
    ]
