# Generated by Django 3.2.5 on 2021-08-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_auto_20210808_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='meals',
            options={'verbose_name': 'Məhsul', 'verbose_name_plural': 'Məhsullar'},
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='categorya',
            new_name='category',
        ),
    ]
