# Generated by Django 3.2.5 on 2021-08-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_auto_20210809_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
