# Generated by Django 3.2.5 on 2021-08-14 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_remove_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kateqoriya', 'verbose_name_plural': 'Kateqoriyalar'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.category', verbose_name='Kateqoriya'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Haqqında'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='image',
            field=models.ImageField(upload_to='meals', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='people',
            field=models.IntegerField(verbose_name='Adam sayı'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='pre_time',
            field=models.IntegerField(verbose_name='Hazırlanma vaxtı'),
        ),
    ]
