# Generated by Django 3.2.5 on 2021-08-17 10:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_alter_meals_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Haqqında'),
        ),
    ]
