# Generated by Django 3.2.5 on 2021-08-16 08:47

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_stuff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[700, 730], upload_to=''),
        ),
    ]
