# Generated by Django 3.2.5 on 2021-08-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Paramter', 'verbose_name_plural': 'Parametrlər'},
        ),
    ]
