# Generated by Django 3.2.5 on 2021-08-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_settings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='contanctinf',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Əlaqə Məlumatları'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone',
            field=models.TextField(max_length=100, verbose_name='Telefon'),
        ),
    ]
