# Generated by Django 3.2.5 on 2021-08-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20210814_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='phone',
        ),
        migrations.AddField(
            model_name='settings',
            name='phone2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefon'),
        ),
    ]
