# Generated by Django 3.2.5 on 2021-08-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20210814_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='phone',
            field=models.IntegerField(default=1, verbose_name='Telefon1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefon2'),
        ),
    ]
