# Generated by Django 3.2.5 on 2021-08-14 14:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_auto_20210814_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='about',
            field=ckeditor.fields.RichTextField(max_length=10000, verbose_name='Haqqında'),
        ),
    ]
