# Generated by Django 3.2.5 on 2021-08-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_alter_settings_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Mesaj', 'verbose_name_plural': 'Mesajlar'},
        ),
    ]
