# Generated by Django 3.2.5 on 2021-08-16 11:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_contactus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='about_short',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Kiçik hekayə'),
            preserve_default=False,
        ),
    ]
