# Generated by Django 3.2.5 on 2021-08-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postbloq', '0002_auto_20210813_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alem',
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
