# Generated by Django 3.2.5 on 2021-08-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postbloq', '0004_alem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alem',
        ),
    ]
