# Generated by Django 3.2.5 on 2021-08-14 14:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postbloq', '0005_delete_alem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=5000),
        ),
    ]
