# Generated by Django 3.2.5 on 2021-08-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postbloq', '0008_auto_20210816_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
