# Generated by Django 3.2.5 on 2021-08-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_delete_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Reservasiya', 'verbose_name_plural': 'Rezervasiyalar'},
        ),
    ]
