# Generated by Django 3.2.5 on 2021-08-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='people',
            field=models.TextField(choices=[('1 nəfərlik', '1 nəfərlik'), ('2 nəfərlik', '2 nəfərlik'), ('3 nəfərlik', '3 nəfərlik'), ('4 nəfərlik', '4 nəfərlik'), ('5 nəfərlik', '5 nəfərlik'), ('6 nəfərlik', '6 nəfərlik'), ('7 nəfərlik', '7 nəfərlik'), ('8 nəfərlik', '8 nəfərlik')]),
        ),
    ]
